/**
 * Group profile - Payments tab.
 *
 * GET /api/groups/{id}/finance-summary/ returns one billing period at a time
 * (`period_start` defaults to the first of the current month on the server).
 * Each row is an invoice summary for a student in this group: what they were
 * billed, what they paid and what is left. Money is always rendered through the
 * settings-aware formatter, so the centre's own currency and decimals apply.
 */

import { useMemo, useState } from 'react';
import {
  Button,
  Card,
  DateField,
  StatCard,
  StatusBadge,
  Table,
  type TableColumn,
} from '../../components';
import { Link } from 'react-router-dom';
import { useSettings } from '../../settings/SettingsContext';
import { groupsApi, toNumber, type Group, type InvoiceSummary } from '../students/api';
import { useAsyncResource } from '../students/hooks';
import { AsyncSection, RecordLink } from '../students/ui';

export interface GroupPaymentsTabProps {
  group: Group;
}

export function GroupPaymentsTab({ group }: GroupPaymentsTabProps) {
  const settings = useSettings();
  const [periodStart, setPeriodStart] = useState('');

  const resource = useAsyncResource(
    () =>
      groupsApi.financeSummary(group.id, {
        period_start: periodStart === '' ? undefined : periodStart,
      }),
    `group-finance:${group.id}:${periodStart}`,
  );

  const data = resource.data;
  const rows = useMemo(() => data?.students ?? [], [data]);

  const columns = useMemo<ReadonlyArray<TableColumn<InvoiceSummary>>>(
    () => [
      {
        key: 'student_name',
        header: 'Student',
        render: (row) => (
          <span className="cell-stack">
            <RecordLink to={`/students/${row.student}`}>{row.student_name}</RecordLink>
            <span className="cell-stack__secondary u-mono">{row.student_code}</span>
          </span>
        ),
      },
      {
        key: 'period',
        header: 'Period',
        width: '120px',
        render: (row) => <span className="u-nowrap">{row.period}</span>,
      },
      {
        key: 'due_date',
        header: 'Due',
        width: '130px',
        render: (row) => (
          <span className="cell-stack">
            <span className="u-nowrap">{settings.date(row.due_date)}</span>
            {row.days_overdue > 0 ? (
              <span className="cell-stack__secondary">
                {settings.number(row.days_overdue)} days overdue
              </span>
            ) : null}
          </span>
        ),
      },
      {
        key: 'amount_due',
        header: 'Billed',
        align: 'right',
        width: '140px',
        render: (row) => <span className="u-nowrap">{settings.money(toNumber(row.amount_due))}</span>,
      },
      {
        key: 'amount_paid',
        header: 'Paid',
        align: 'right',
        width: '140px',
        render: (row) => <span className="u-nowrap">{settings.money(toNumber(row.amount_paid))}</span>,
      },
      {
        key: 'remaining',
        header: 'Remaining',
        align: 'right',
        width: '140px',
        render: (row) => <strong className="u-nowrap">{settings.money(toNumber(row.remaining))}</strong>,
      },
      {
        key: 'status',
        header: 'Status',
        width: '120px',
        render: (row) => <StatusBadge status={row.status} />,
      },
    ],
    [settings],
  );

  const toolbar = (
    <div className="toolbar-split">
      <DateField
        label="Period starts"
        labelHidden
        small
        value={periodStart}
        onChange={setPeriodStart}
      />
      {periodStart !== '' ? (
        <Button size="sm" icon="close" onClick={() => setPeriodStart('')}>
          Current period
        </Button>
      ) : null}
      <span className="toolbar-split__spacer" />
      <Button size="sm" icon="refresh" onClick={resource.reload}>
        Reload
      </Button>
    </div>
  );

  return (
    <AsyncSection
      loading={resource.loading}
      error={resource.error}
      onRetry={resource.reload}
      isEmpty={data !== null && rows.length === 0}
      emptyIcon="wallet"
      emptyTitle="No invoices for this period"
      emptyMessage={
        periodStart !== ''
          ? 'No invoice was raised for this group in the selected billing period.'
          : 'Invoices for this group are generated by the Finance module; once billed they appear here.'
      }
      loadingRows={5}
    >
      {data === null ? null : (
        <div className="section-stack">
          <div className="kpi-grid">
            <StatCard
              label="Billed"
              icon="clipboard"
              value={settings.money(toNumber(data.amount_due))}
              hint={`Period starting ${settings.date(data.period_start)}`}
            />
            <StatCard label="Collected" icon="wallet" value={settings.money(toNumber(data.amount_paid))} />
            <StatCard
              label="Outstanding"
              icon="alert"
              value={settings.money(toNumber(data.outstanding))}
              hint={data.unpaid_count > 0 ? 'Chase these students' : 'Nothing outstanding'}
            />
            <StatCard label="Paid in full" icon="checkCircle" value={settings.number(data.paid_count)} />
            <StatCard label="Still owing" icon="info" value={settings.number(data.unpaid_count)} />
          </div>

          <Card
            flush
            title="Per student"
            subtitle={`Billing period starting ${settings.date(data.period_start)} · an empty period means nothing has been invoiced yet`}
            actions={
              <Link className="btn btn--secondary btn--sm" to={`/students?group=${group.id}`}>
                Open students
              </Link>
            }
          >
            <Table<InvoiceSummary>
              columns={columns}
              rows={rows}
              rowKey={(row) => row.id}
              paginated={rows.length > 25}
              initialPageSize={25}
              dense
              stickyHeader
              toolbar={toolbar}
              caption="Group billing"
              emptyIcon="wallet"
              emptyTitle="No invoices for this period"
              emptyMessage="Nobody in this group has an invoice for the selected period."
            />
          </Card>
        </div>
      )}
    </AsyncSection>
  );
}

export default GroupPaymentsTab;
