# Generated by Django 5.2.17 on 2026-09-20 17:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_name', models.CharField(default='Learning Centre', max_length=160)),
                ('logo_url', models.URLField(blank=True)),
                ('currency_code', models.CharField(default='UZS', max_length=8)),
                ('currency_symbol', models.CharField(default="so'm", max_length=8)),
                ('currency_decimals', models.PositiveSmallIntegerField(default=0)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=64)),
                ('default_billing_day', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('attendance_threshold_pct', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('absence_alert_count', models.PositiveSmallIntegerField(default=3)),
                ('absence_streak_alert_count', models.PositiveSmallIntegerField(default=3)),
                ('failing_exam_alert_count', models.PositiveSmallIntegerField(default=2)),
                ('default_passing_score_pct', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('academic_year_start', models.DateField(blank=True, null=True)),
                ('academic_year_end', models.DateField(blank=True, null=True)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('lead_sources', models.JSONField(blank=True, default=list)),
                ('income_categories', models.JSONField(blank=True, default=list)),
                ('expense_categories', models.JSONField(blank=True, default=list)),
                ('notification_channels', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System settings',
                'verbose_name_plural': 'System settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=160)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('permission', 'Permission change'), ('approve', 'Approve'), ('pay', 'Payment recorded'), ('void', 'Void')], max_length=24)),
                ('entity', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='core_auditl_entity_d1c59f_idx'), models.Index(fields=['actor', '-created_at'], name='core_auditl_actor_i_502baf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_scope', models.CharField(blank=True, db_index=True, max_length=32)),
                ('kind', models.CharField(choices=[('payment_overdue', 'Payment overdue'), ('attendance_warning', 'Attendance warning'), ('exam_scheduled', 'Exam scheduled'), ('exam_result', 'Exam result published'), ('payroll_pending', 'Payroll pending'), ('schedule_conflict', 'Schedule conflict'), ('attendance_incomplete', 'Incomplete attendance'), ('system', 'System')], default='system', max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, help_text='In-app route the alert points at', max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(blank=True, help_text='Null means the notification is addressed to a role/all staff.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='core_notifi_recipie_43dea6_idx')],
            },
        ),
    ]
