# Generated by Django 5.2.17 on 2026-09-20 17:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False, help_text='Closed periods are not re-billed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-period_start',),
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='billing_period_valid_range')],
            },
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('period_label', models.CharField(db_index=True, max_length=32)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived'), ('cancelled', 'Cancelled')], db_index=True, default='unpaid', max_length=16)),
                ('waived_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='academics.group')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance.billingperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='academics.student')),
            ],
            options={
                'ordering': ('-period_start', 'student__first_name'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_at', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('online', 'Online'), ('other', 'Other')], default='cash', max_length=24)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_void', models.BooleanField(db_index=True, default=False)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='academics.student')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_voided', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.studentinvoice')),
            ],
            options={
                'ordering': ('-paid_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('teacher_salaries', 'Teacher Salaries'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('internet', 'Internet'), ('marketing', 'Marketing'), ('equipment', 'Equipment'), ('office_supplies', 'Office Supplies'), ('maintenance', 'Maintenance'), ('software', 'Software'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('category_label', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('online', 'Online'), ('other', 'Other')], default='cash', max_length=24)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-id'),
                'indexes': [models.Index(fields=['date', 'category'], name='finance_exp_date_8ba413_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='expense_amount_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('student_fees', 'Student Fees'), ('registration_fees', 'Registration Fees'), ('exam_fees', 'Exam Fees'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('category_label', models.CharField(blank=True, help_text='Free-text category override', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('online', 'Online'), ('other', 'Other')], default='cash', max_length=24)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='academics.student')),
            ],
            options={
                'ordering': ('-date', '-id'),
                'indexes': [models.Index(fields=['date', 'category'], name='finance_inc_date_0ba110_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.00'))), name='income_amount_non_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['status', 'due_date'], name='finance_stu_status_056e04_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['student', '-period_start'], name='finance_stu_student_704186_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.UniqueConstraint(fields=('student', 'period_start'), name='unique_invoice_per_student_period'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='invoice_valid_period'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', '-paid_at'], name='finance_pay_student_d75e53_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at', 'is_void'], name='finance_pay_paid_at_1c717f_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('is_void', False), models.Q(('void_reason', ''), _negated=True), _connector='OR'), name='voided_payment_requires_reason'),
        ),
    ]
