# Generated by Django 5.2.17 on 2026-09-20 17:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('exam_type', models.CharField(choices=[('quiz', 'Quiz'), ('monthly_test', 'Monthly test'), ('midterm', 'Midterm'), ('final', 'Final'), ('mock_exam', 'Mock exam'), ('placement_test', 'Placement test'), ('custom', 'Custom')], db_index=True, default='custom', max_length=24)),
                ('date', models.DateField(db_index=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('passing_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.group')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academics.teacher')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ExamComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='exams.exam')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('grade', models.CharField(blank=True, max_length=4)),
                ('teacher_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(blank=True, help_text='Null marks the overall result of the exam.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.examcomponent')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results_marked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.student')),
            ],
            options={
                'ordering': ('student__first_name', 'student__last_name', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['group', '-date'], name='exams_exam_group_i_ec1e38_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type', 'date'], name='exams_exam_exam_ty_d7e177_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['is_published', 'date'], name='exams_exam_is_publ_f9430c_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='exam_max_score_positive'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('passing_score__gte', 0)), name='exam_passing_score_non_negative'),
        ),
        migrations.AddIndex(
            model_name='examcomponent',
            index=models.Index(fields=['exam', 'order'], name='exams_examc_exam_id_24fa55_idx'),
        ),
        migrations.AddConstraint(
            model_name='examcomponent',
            constraint=models.UniqueConstraint(fields=('exam', 'name'), name='unique_component_name_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='examcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='exam_component_max_score_positive'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'student'], name='exams_examr_exam_id_b70e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', '-created_at'], name='exams_examr_student_d606e4_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'component'], name='exams_examr_exam_id_9734fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'component', 'student'), name='unique_result_per_component'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(condition=models.Q(('component__isnull', True)), fields=('exam', 'student'), name='unique_overall_result_per_exam'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='exam_result_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='exam_result_percentage_range'),
        ),
    ]
