# Generated by Django 5.2.17 on 2026-09-20 17:36

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=64)),
                ('default_monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('duration_months', models.PositiveSmallIntegerField(default=0, help_text='0 means open-ended')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(default=datetime.date.today)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left'), ('transferred', 'Transferred')], default='active', max_length=16)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-joined_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relation', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('other', 'Other')], default='guardian', max_length=16)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)])),
                ('location', models.CharField(blank=True, max_length=120)),
                ('equipment', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=24, unique=True)),
                ('first_name', models.CharField(db_index=True, max_length=80)),
                ('last_name', models.CharField(db_index=True, max_length=80)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unspecified', 'Not specified')], default='unspecified', max_length=16)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('trial', 'Trial'), ('active', 'Active'), ('paused', 'Paused'), ('graduated', 'Graduated'), ('dropped', 'Dropped'), ('archived', 'Archived')], db_index=True, default='active', max_length=16)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateField(default=datetime.date.today)),
                ('left_at', models.DateField(blank=True, help_text='Set when a student drops or graduates', null=True)),
                ('leave_reason', models.CharField(blank=True, max_length=255)),
                ('monthly_fee_override', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-is_pinned', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('specialization', models.CharField(blank=True, max_length=160)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full_time', max_length=16)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('graduated', 'Graduated'), ('dropped', 'Dropped'), ('archived', 'Archived')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='TeacherGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-from_date',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=15)),
                ('level', models.CharField(blank=True, max_length=64)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('graduated', 'Graduated'), ('dropped', 'Dropped'), ('archived', 'Archived')], db_index=True, default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.course')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
