# Generated by Django 5.2.17 on 2026-09-20 17:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='academics.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='academics.room'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.guardian'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='academics.student'),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_entries', to='academics.student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='academics.teacher'),
        ),
        migrations.AddField(
            model_name='teachergroupassignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.group'),
        ),
        migrations.AddField(
            model_name='teachergroupassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.teacher'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='academics_s_last_na_868c57_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'registered_at'], name='academics_s_status_f3a25a_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_fee_override__isnull', True), ('monthly_fee_override__gte', Decimal('0.00')), _connector='OR'), name='student_fee_non_negative'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'left_at'], name='academics_g_group_i_718780_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['student', 'left_at'], name='academics_g_student_a57654_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('student', 'group'), name='unique_active_membership_per_group'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('left_at__gte', models.F('joined_at')), _connector='OR'), name='membership_left_after_joined'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['student', '-created_at'], name='academics_s_student_9243d6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['status'], name='academics_t_status_ae9761_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['status', 'course'], name='academics_g_status_faccd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='teachergroupassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'group', 'from_date'), name='unique_teacher_group_assignment'),
        ),
    ]
