# Generated by Django 5.2.17 on 2026-09-20 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=160)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(blank=True, db_index=True, help_text='Chosen from SystemSettings.lead_sources at runtime, never hard-coded.', max_length=64)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('trial_scheduled', 'Trial scheduled'), ('trial_completed', 'Trial completed'), ('interested', 'Interested'), ('registered', 'Registered'), ('lost', 'Lost')], db_index=True, default='new', max_length=24)),
                ('trial_date', models.DateField(blank=True, db_index=True, null=True)),
                ('lost_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_student', models.OneToOneField(blank=True, help_text='Set on conversion, guaranteeing one student per lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_conversion', to='academics.student')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
                ('interested_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='academics.course')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('call', 'Call'), ('message', 'Message'), ('trial_scheduled', 'Trial scheduled'), ('trial_completed', 'Trial completed'), ('status_change', 'Status change')], default='note', max_length=24)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='crm_lead_status_18283c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='crm_lead_assigne_36bf8f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'status'], name='crm_lead_source_15caf1_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', '-created_at'], name='crm_leadact_lead_id_639066_idx'),
        ),
    ]
